### PR TITLE
add wrapper for managed object request

### PR DESCRIPTION
**Pull request by TheSooth**

### CODE REVIEW

**Comment by cmckni3** [comment]
:+1:

**Comment by cmckni3** [comment]
Thanks!

**Comment by cmckni3** [comment]
Just pushed out version 0.2.0. Cheers

**Comment by TheSooth** [comment]
@cmckni3  np  :beers:

**Comment by cmckni3** [comment]
@TheSooth Just a heads up. I had to wrap it in `#ifdef`. It wouldn't compile in the absence of CoreData and RestKit/CoreData.

If you're curious, see https://github.com/cmckni3/RestKit-PromiseKit/blob/master/RestKit-PromiseKit/RKObjectManager%2BPromiseKit.m#L104

**Pull request merged**
